config/routes.rb
Rails.application.routes.draw do

  root 'stores#index'

  get 'stores/faq' => 'stores#faq'

  get 'stores/about' => 'stores#about'

  resources :stores

end

app/models/store.rb
class Store < ActiveRecord::Base
  validates :location_address, :uniqueness => true

  before_create :clean_address

  private
  def clean_address
    address = JSON.parse(self.location_address)
    self.location_address = address.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def index
    @stores = Store.all

    gon.stores = @stores
    gon.baskin_robbins = @baskin_robbins
  end

  def show
    @store = Store.find(params[:id])
    render layout: "show"
  end

  private
  def store_params
    params.require(:store).permit(:name, :image_url, :display_phone, :review_count, :location_address, :location_city, :owner_id, :rating_img_url, :description, :location_neighborhoods, :longitude, :latitude, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Frotogo" %></title>

    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Hind:600" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?v=3.23&key=AIzaSyB0Ym_ZexOZYC3qENOj3pzdSchvXb5Ris4&callback=initIndexMap", async: true, defer: true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header class="header">
    </header>

  <div id="logo_div">

    <%= link_to "froTOgo", root_path, id: "logo" %>

  </div>

    <%= yield %>

  <footer>
    <div class="center_logo">
    <%= link_to "froTOgo", root_path, id: "logo_bottom" %>
    </div>

    <p>© 2016 Frotogo Ltd.</p>

    <div class="footer_menu">
      <ul>
        <li><%= link_to "FAQ", stores_faq_path %></li>
        <li><%= link_to "ABOUT", stores_about_path %></li>
      </ul>
    </div>

  </footer>

  </body>
</html>

app/views/layouts/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Frotogo" %></title>

    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?v=3.23&key=AIzaSyB0Ym_ZexOZYC3qENOj3pzdSchvXb5Ris4&callback=initShowMap", async: true, defer: true %>
    <!-- <%= javascript_include_tag "https://maps.google.com/maps/api/js?v=3.23&key=AIzaSyB0Ym_ZexOZYC3qENOj3pzdSchvXb5Ris4&callback=initIndexMap", async: true, defer: true %> -->
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header class="header">
    </header>

  <div id="logo_div">

    <%= link_to "froTOgo", root_path, id: "logo" %>

  </div>

    <%= yield %>

  <footer>
    <div class="center_logo">
    <%= link_to "froTOgo", root_path, id: "logo_bottom" %>
    </div>

    <p>© 2016 Frotogo Ltd.</p>

    <div class="footer_menu">
      <ul>
        <li><%= link_to "FAQ", stores_faq_path %></li>
        <li><%= link_to "ABOUT", stores_about_path %></li>
      </ul>
    </div>

  </footer>

  </body>
</html>

app/views/stores/about.html.erb
<style>

  p {
    font-family: 'Hind', sans-serif;
    font-size: 1.6em;
    line-height: 1.4em;
    color: #223EA5;
  }

  #bowtie {
    float:left;
    width: 250px;
    border: 3px solid #fff;
    border-radius: 5px;
    margin: 8px;
    margin-top: 0;
  }
  #jesus {
    float:right;
    width: 200px;
    border: 3px solid #fff;
    border-radius: 5px;
    margin: 8px;
  }
</style>

<br/>



<div class="biglogo">
  <img src="/assets/frotogo.png"/>
</div>

<div class="big_box_about">
  <img src="/assets/bowtie.jpg" id="bowtie" /><p><b>froTOgo</b> became what it is today because one day I was in the right place at the wrong time, literally. When I started attending coding bootcamp at Bitmaker Labs, I was pleasantly surprised to see a traditional ice cream truck parked across the road every day. I began to enjoy the occasional delicious dipped soft serve cone, prepared by a nice guy in a bow tie.</p>

<p>One hot afternoon, when the craving for a treat emerged after completing a tough assignment, I stepped out onto King St and the truck was nowhere to be seen. Disappointed, I was reminded that street parking rules are different here in the city core and the truck had to be gone by 3pm. Forced to seek out a cone nearby using my phone, I found a place called Sweet Jesus just around the corner. Lucky me!</p><img src="/assets/jesus.jpg" id="jesus" />
  <p>Little did I know these gourmet cone shops were so popular, a crowd of devoted fans lined up down the street for unique decadent cones with over-the-top themed toppings. Intrigued, I stepped into line and began researching the ice cream craze that exists in Toronto.</p>

<p>After reading a few articles about the unique scene the city has embraced, I was convinced that froTOgo was just waiting to be built. Frozen treat fans deserve a full interactive directory of shops in the city to satisfy their cravings right away, whether it's a gelato bar, hard ice cream scooped high, a crazy twist of froyo flavours, or a unique dessert imported from the global community here in Toronto. froTOgo's life has just begun and there are many more features on the way. Enjoy! &nbsp;&nbsp;- Brian</p>
<br>
<p><small>Site developed by Brian Harrison and Daniel Valle.
<br>
Site features provided by Yelp and Google Maps.</small></p>
<br>
</div>
<div>
  <br />
  <br />
  <br />
  <br />
</div>

app/views/stores/faq.html.erb
<style>
  .faq {
    margin-left: 20px;
}
  .faqlist {
    font-family: 'Hind', sans-serif;
    font-size: 1.35em;
    line-height: 1.5em;
    color: #223EA5;
  }
  p {
    font-family: 'Hind', sans-serif;
    font-size: 1.35em;
    line-height: 1.5em;
    color: #223EA5;
  }
</style>

  <br>
<br>
<br>
<div class="faq">
  <h1 style="color: #223EA5;">Welcome to the froTOgo FAQ:</h1>
<br>
&nbsp;&nbsp;&nbsp;<p>Here you will find the answers to questions that frozen treat lovers like you would ask in Toronto:<br>
Some examples...</p>
<ul class="faqlist">
  <li>Can I get my frozen fix at Pearson Airport?</li>
  <li>What's the best frozen treat for a family day at Canada's Wonderland?</li>
  <li>Where can I find ice cream under downtown's streets in the PATH system?</li>
  <li>How do I cool off with a chilly treat at the Toronto Zoo?</li>
  <li>Is there somewhere on Centre Island to get a round of fro to go?</li>
  <li>Where can I get a cone when I'm visiting the Lakeshore West area?</li>
  <li>What are some of the top spots for fro to go in the GTA?</li>
</ul>
<br>

  <p>All these answers and more coming soon on our FAQ page.</p>
</div>

app/views/stores/show.html.erb
  <div class="store_container">

  <div class="store_title">
    <h1 id="store_name"><%= @store.name.titleize %></h1>
</div>
  <img src="<%= @store.image_url %>" id="store_image">
  <hr id="store_line" />

    <div class="store_details">

    <p id="address"> <%= @store.location_address %></p>

    <p><a href="tel:<%= @store.display_phone %>" id="phone">
      <% if @store.display_phone != nil %>
      <%= @store.display_phone[3..-1] %>
      <% else %>
      <% end %>
    </a></p>

    <p id="snippet_1"> Review Snippet: </p>
    <p id="snippet_2"> <%= @store.snippet_text %> </p>

    <a href="<%= @store.url %>" id="rating">Yelp Rating: <%= @store.rating %></p>
    <%= image_tag @store.rating_img_url, class: "rating_image" %>

    <a href="<%= @store.url %>" id="yelp_reviews" target="_blank"> <%= @store.review_count %> Reviews on Yelp </a>

  </div>

  <div id="map_show" data-name = "<%= @store.name %>" data-latitude= "<%= @store.latitude %>" data-longitude= "<%= @store.longitude %>" data-location= "<%= @store.location_address %>" >
  </div>

  </div>